spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work_hub
    username: corporate
    password: corporate
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql





